spring:
  application:
    name: eureka-provider

server:
  port: 7081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
      
logging:
  file: ${spring.application.name}.log