spring:
  application:
    name: eureka-consumer-ribbon
    
server:
  port: 7092
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
      
logging:
  file: ${spring.application.name}.log