spring:
  application:
    name: eureka-consumer
    
server:
  port: 7091
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
      
logging:
  file: ${spring.application.name}.log